"""Shared style and data access for the paper figures.

Every figure in the manuscript is generated by ``make_figures.py`` through this
module. The style is set once here so the figures form one system: a serif face
matching the Times body text, 8 pt base size, hairline rules, and a palette that
stays distinguishable in greyscale and under the common colour-vision
deficiencies.

Figure widths are given in inches against the ICLR text block (5.5 in), so
nothing is rescaled by ``includegraphics`` and the type size in the figure
matches the type size on the page.
"""
from __future__ import annotations

import itertools
import json
import re
from pathlib import Path

from datetime import datetime, timezone

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

# ------------------------------------------------------------------ constants
TEXT_WIDTH = 5.5           # ICLR text block, inches
# Gaussian stability threshold of the resource landscape, as the runs used it.
# This is computed from the SHIPPED B(b), which _kde_on_grid returns near-uniform
# over the lattice rather than as a density of the prompt cloud (it divides each
# grid point by its own nearest-prompt kernel value). Solving against the
# empirical prompt measure instead gives 0.36905. Every run used the value below,
# so it stays; figures label it sigma-hat to avoid asserting the other one.
SIGMA_STAR = 0.40977
SIGMA_STAR_EMPIRICAL = 0.36905
FINAL_ROUND = 11
REPO = Path(__file__).resolve().parents[1]
RESULTS = REPO / "results"
PAPER = Path(__file__).resolve().parent
OUT = PAPER / "figures"
DATA = PAPER / "data"

AXES_SHORT = ["HRM", "HAL", "JBK", "PRV", "ORF", "INJ", "POL"]
AXES_LONG = ["harm", "hallucination", "jailbreak", "privacy",
             "over-refusal", "injection", "policy"]

# Sigma arms, ordered by competitive reach.
SIGMA_ARMS = [
    (0.70, "seven_axis_sigma07_full"), (0.60, "seven_axis_sigma06_full"),
    (0.55, "seven_axis_sigma055_full"), (0.50, "seven_axis_soft_full_pairs"),
    (0.45, "seven_axis_sigma045_full"), (0.40, "seven_axis_sigma04_full"),
    (0.30, "seven_axis_sigma03_full"), (0.20, "seven_axis_sigma02_full"),
    (0.10, "seven_axis_sigma01_full"), (0.05, "seven_axis_sigma005_full"),
]

# Routing ablation arms: label, run, selection rule, k, loss weighting.
ROUTING_ARMS = [
    ("Soft $k{=}7$, weighted", "seven_axis_soft_full_pairs", "argmax (all)", 7, "share"),
    ("Soft $k{=}3$, weighted", "seven_axis_soft_topk3_pairs", "argmax top-3", 3, "share"),
    ("Soft $k{=}3$, unit", "seven_axis_topk3_unit_pairs", "argmax top-3", 3, "unit"),
    ("Sampled $k{=}3$, unit", "seven_axis_hard_topk3_pairs", "sampled", 3, "unit"),
    ("Hard $k{=}1$ (SFT)", "seven_axis_hard_pairs_matched", "sampled winner", 1, "unit"),
]

# Base models: label, run, parameter count in billions.
SCALE_ARMS = [
    ("Qwen2.5-1.5B", "seven_axis_soft_full_pairs", 1.5, "Qwen2.5"),
    ("Qwen2.5-3B", "seven_axis_soft_full_3b", 3.0, "Qwen2.5"),
    ("Qwen2.5-7B", "seven_axis_soft_full_7b", 7.0, "Qwen2.5"),
    ("Llama-3.2-1B", "seven_axis_soft_full_llama1b", 1.2, "Llama-3.2"),
    ("Gemma-3-1B", "seven_axis_soft_full_gemma3_1b", 1.0, "Gemma-3"),
]

# Pair-count ablation: number of routing pairs, run. Seed 0 only. Seven pairs is
# the standard arm, so it doubles as the 7-pair point.
PAIR_ARMS = [
    (2, "seven_axis_2pair_sigma05"), (3, "seven_axis_3pair_sigma05"),
    (4, "seven_axis_4pair_sigma05"), (5, "seven_axis_5pair_sigma05"),
    (6, "seven_axis_6pair_sigma05"), (7, "seven_axis_soft_full_pairs"),
    (8, "seven_axis_8pair_sigma05"), (9, "seven_axis_9pair_sigma05"),
]

# Theory-equilibrium arms: the same pair-count ablation restarted from an
# equilibrium of the influencer game solved against the EMPIRICAL prompt cloud.
# The original arms start from a near-uniform prior over the lattice -- an
# uninformative "naive start" -- because _kde_on_grid returns a flat weight
# vector (it divides each grid point by its own nearest-prompt kernel value).
# So the contrast is naive start vs game equilibrium, one factor, same split.
THEORY_EQ_PAIR_ARMS = [
    (2, "seven_axis_theory_eq_2pair"), (3, "seven_axis_theory_eq_3pair"),
    (4, "seven_axis_theory_eq_4pair"), (5, "seven_axis_theory_eq_5pair"),
    (6, "seven_axis_theory_eq_6pair"), (7, "seven_axis_theory_eq"),
    (8, "seven_axis_theory_eq_8pair"), (9, "seven_axis_theory_eq_9pair"),
]

# Where the original pair-count ablation's gain curve steps up. The theory-eq
# arms move the step, so it is drawn rather than assumed.
PAIR_THRESHOLD = 4.5

# Data-split replicates only. ``seed1``/``seed2`` are run-seed replicates on the
# seed-0 split, so they share its test pool and must not be pooled with the
# dseeds as if they were independent splits.
SEED_RE = re.compile(r"^(seed0|dseed\d+)$")

# sigma 0.50 is the project's standard arm and its seed-0 run predates the sweep
# naming, so it sits under seven_axis_soft_full_pairs while its replicates were
# written under seven_axis_sigma05_full. Both are the same configuration; a
# sweep point has to gather from every name it has ever been stored under or the
# 0.50 column silently reports n=1.
SIGMA_RUN_ALIASES = {0.50: ["seven_axis_soft_full_pairs", "seven_axis_sigma05_full"]}

# The reach sweep restarted from the game equilibrium, by data split. Unlike the
# naive arms, the second split is a SEPARATE RUN DIRECTORY whose subdirectory is
# still called "seed0" (the run seed is what dseed1 changes, plus the manifest),
# so seeds_for cannot discover it -- the split has to be named explicitly.
#
# Every one of these is scored on the identical test pool (n=5671, pooled
# 2.0152) as its naive counterpart at the same reach, so unlike the cross-split
# sigma figures these contrasts are PAIRED: the same prompts, the same
# generalist, one factor moved.
THEORY_EQ_SIGMA_ARMS = {
    0.05: {"seed0": "seven_axis_theory_eq_sigma005",
           "dseed1": "seven_axis_theory_eq_sigma005_d1"},
    0.10: {"seed0": "seven_axis_theory_eq_sigma01",
           "dseed1": "seven_axis_theory_eq_sigma01_d1"},
    0.20: {"seed0": "seven_axis_theory_eq_sigma02",
           "dseed1": "seven_axis_theory_eq_sigma02_d1"},
    0.30: {"seed0": "seven_axis_theory_eq_sigma03",
           "dseed1": "seven_axis_theory_eq_sigma03_d1"},
    0.40: {"seed0": "seven_axis_theory_eq_sigma04",
           "dseed1": "seven_axis_theory_eq_sigma04_d1"},
    0.45: {"seed0": "seven_axis_theory_eq_sigma045",
           "dseed1": "seven_axis_theory_eq_sigma045_d1"},
    0.50: {"seed0": "seven_axis_theory_eq",
           "dseed1": "seven_axis_theory_eq_sigma05_d1"},
    0.55: {"seed0": "seven_axis_theory_eq_sigma055",
           "dseed1": "seven_axis_theory_eq_sigma055_d1"},
    0.60: {"seed0": "seven_axis_theory_eq_sigma06",
           "dseed1": "seven_axis_theory_eq_sigma06_d1"},
    0.70: {"seed0": "seven_axis_theory_eq_sigma07",
           "dseed1": "seven_axis_theory_eq_sigma07_d1"},
}

# Reach 0.70's equilibrium is degenerate -- seven pairs collapse onto five
# distinct positions and hold there for all twelve rounds -- so it is excluded
# from smoothness statistics, which would otherwise be dominated by it.
SIGMA_DEGENERATE = 0.70

# ------------------------------------------------------------------- palette
INK = "#1a1a1a"
INK_2 = "#555555"
INK_3 = "#8a8a8a"
GRID = "#d9d9d9"
C_ORACLE = "#2a78d6"
C_ROUTER = "#eb6834"
C_POOLED = "#7b8786"
C_ACCENT = "#0b8f84"
C_WARN = "#b0341f"
SEQ = ["#04413b", "#0b8f84", "#5cc6bb"]

# One hue per trait axis, for the radars. Seven categorical hues cannot all be
# told apart under the common colour-vision deficiencies, so colour here is
# always redundant with a text cue (the dominant spoke label is bolded in the
# same hue) and never the only channel.
AXIS_COLORS = ["#2a78d6", "#eb6834", "#0b8f84", "#8a5fbf",
               "#b0341f", "#5c8a1f", "#c9871f"]


def use_paper_style() -> None:
    """Apply the manuscript's rcParams. Call once before building any figure."""
    plt.rcParams.update({
        "font.family": "serif",
        "font.serif": ["Nimbus Roman", "Times New Roman", "DejaVu Serif"],
        "mathtext.fontset": "stix",
        "font.size": 8,
        "axes.titlesize": 8,
        "axes.labelsize": 8,
        "xtick.labelsize": 7,
        "ytick.labelsize": 7,
        "legend.fontsize": 7,
        "axes.linewidth": 0.6,
        "axes.edgecolor": "#8a8a8a",
        "axes.labelcolor": INK,
        "axes.titleweight": "bold",
        "text.color": INK,
        "xtick.color": INK_2,
        "ytick.color": INK_2,
        "xtick.major.width": 0.6,
        "ytick.major.width": 0.6,
        "xtick.major.size": 2.5,
        "ytick.major.size": 2.5,
        "lines.linewidth": 1.1,
        "lines.markersize": 4,
        "grid.color": GRID,
        "grid.linewidth": 0.5,
        "legend.frameon": False,
        "figure.dpi": 200,
        "savefig.dpi": 200,
        "savefig.bbox": "tight",
        "savefig.pad_inches": 0.01,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
    })


def despine(ax, keep=("left", "bottom")) -> None:
    """Drop the box down to the axes that carry a scale."""
    for side in ("top", "right", "left", "bottom"):
        ax.spines[side].set_visible(side in keep)


def true_theory(run: str) -> dict | None:
    """Theory positions re-solved against the *empirical* resource measure.

    The shipped ``B(b)`` is not a KDE of the prompt cloud: ``_kde_on_grid``
    divides each grid point's density by its own nearest-prompt kernel value, so
    a single prompt returns a uniform vector. What the solve actually optimised
    against is close to a uniform prior over the ``{0,0.5,1}^7`` lattice. Those
    positions are still the ones every run started from, so they are reported as
    the *approximate* initialisation; these are where the same solve lands when
    it sees the real distribution.

    Written by ``paper/true_theory_positions.py`` (CPU, minutes per arm) and
    cached, so figures never pay for the solve. Returns ``None`` until it runs.
    """
    path = DATA / "true_theory_positions.json"
    if not path.is_file():
        return None
    store = json.loads(path.read_text(encoding="utf-8"))
    entry = store.get(run)
    if not entry or not entry.get("pair_positions"):
        return None
    # The solve keys pairs by member, e.g. "pair_clone-0_clone-1"; order by the
    # first member so the ordering is stable. Identity across solves is
    # established by Hungarian matching, not by this order.
    def _first_index(name: str) -> int:
        found = re.findall(r"\d+", name)
        return int(found[0]) if found else 0

    names = sorted(entry["pair_positions"], key=_first_index)
    out = dict(entry)
    out["names"] = names
    out["positions"] = np.array([entry["pair_positions"][n] for n in names],
                                dtype=float)
    return out


def drift_stats(run: str, sub: str = "seed0") -> dict | None:
    """How far one run's pairs moved from the theory solve, and in what sense.

    The theory initialisation is a prediction made from a KDE-weighted lattice
    model of the prompt cloud; the final positions are what routed training
    produced. The difference is the only place the landscape model gets corrected
    by data, so it is reported rather than discarded.

    ``kept_dominant`` asks whether a pair's argmax axis is still the one the
    solve assigned it -- a cheap check on whether the theory's *assignment*, as
    opposed to its geometry, survived training.
    """
    h = history_slim(run, sub)
    if h is None or h.get("theory_positions") is None:
        return None
    theory = np.asarray(h["theory_positions"], dtype=float)
    final = np.asarray(h["positions"][-1], dtype=float)
    drift = final - theory
    dom_theory = np.asarray(h["dominant_axis"])
    own = np.array([drift[i, d] if d >= 0 else np.nan
                    for i, d in enumerate(dom_theory)])
    out = {
        "run": run, "seed": sub, "n_pairs": int(len(final)),
        "l2": np.linalg.norm(drift, axis=1),
        "mean_l2": float(np.linalg.norm(drift, axis=1).mean()),
        "per_axis": drift.mean(axis=0),
        "radius_theory": mean_radius(theory),
        "radius_final": mean_radius(final),
        "own_axis_drift": float(np.nanmean(own)),
        "kept_dominant": int((dom_theory == final.argmax(axis=1)).sum()),
    }

    # Distance to the solve that saw the real prompt distribution. Pair index is
    # not an identity across two separate solves, so match before differencing.
    tt = true_theory(run) if sub == "seed0" else None
    if tt is not None and len(tt["positions"]) == len(final):
        perm, cost = match_pairs(final, tt["positions"])
        matched = tt["positions"][perm]
        d_true = np.linalg.norm(final - matched, axis=1)
        out.update({
            "true_positions": matched,
            "l2_true": d_true,
            "mean_l2_true": float(d_true.mean()),
            "radius_true": mean_radius(matched),
            "match_cost_true": float(cost),
            "sigma0_lattice": tt.get("sigma0_lattice"),
            "sigma0_empirical": tt.get("sigma0_empirical"),
        })
        # How far apart the two solves are. This is the scale the trained drift
        # should be read against: moving 0.24 from the approximate solve means
        # something different if the two solves are 0.05 apart than if they are 0.4.
        perm_t, _ = match_pairs(theory, tt["positions"])
        out["theory_gap"] = float(
            np.linalg.norm(theory - tt["positions"][perm_t], axis=1).mean())
    return out


def better(ax, axis: str = "y", direction: str = "up",
           newline: bool = False) -> None:
    """Say which way is an improvement, in the axis label itself.

    Half of these axes are NLL differences and half are raw NLL, so the good
    direction flips from figure to figure and is not guessable from the label.
    Putting the arrow in the label rather than in a floating annotation keeps it
    from colliding with the data, which is how the first pass got it wrong.

    Pass ``newline`` when the label is already long enough to overrun its own
    axis; the arrow then sits on a second line instead of being clipped.
    """
    arrow = r"$\uparrow$" if direction == "up" else r"$\downarrow$"
    get, put = ((ax.get_ylabel, ax.set_ylabel) if axis == "y"
                else (ax.get_xlabel, ax.set_xlabel))
    current = get()
    if "better" in current:
        return
    sep = "\n" if newline else "  "
    put((current + sep if current else "") + "({} better)".format(arrow))


def save(fig, name: str, meta: dict | None = None, dpi: int = 300) -> Path:
    """Write one figure as vector PDF, raster PNG, and a provenance sidecar.

    The PDF is what ``main.tex`` includes. The PNG is what the explanatory
    artifact embeds, so both come from one render and cannot drift. The JSON
    sidecar records which runs and seeds went in, so a figure can always be
    traced back to its inputs.
    """
    OUT.mkdir(parents=True, exist_ok=True)
    path = OUT / f"{name}.pdf"
    fig.savefig(path)
    fig.savefig(OUT / f"{name}.png", dpi=dpi)
    plt.close(fig)
    if meta is not None:
        payload = dict(meta)
        payload["generated"] = datetime.now(timezone.utc).isoformat(timespec="seconds")
        (OUT / f"{name}.json").write_text(
            json.dumps(payload, indent=2, sort_keys=True, default=str),
            encoding="utf-8",
        )
    print(f"  wrote {path.relative_to(REPO)} (+.png{'' if meta is None else ' +.json'})")
    return path


# --------------------------------------------------------------- data access
def diagnostics(run: str, sub: str = "seed0") -> dict | None:
    """Routing diagnostics for one arm, or None when the arm has not been run."""
    path = RESULTS / run / sub / "routing_ensemble_diagnostics.json"
    if not path.exists():
        return None
    return json.loads(path.read_text())["flat"]


def positions(run: str, sub: str = "seed0") -> np.ndarray | None:
    """Final-round pair positions, ordered by pair index, shape (n_pairs, L)."""
    path = RESULTS / run / sub / "history.json"
    if not path.exists():
        return None
    entry = json.loads(path.read_text())[-1]["pair_positions"]
    keys = sorted(entry, key=lambda s: int(s.split("-")[1]))
    return np.array([entry[k] for k in keys])


def mean_radius(pos: np.ndarray) -> float:
    """Mean distance of the pair positions from their own centroid."""
    return float(np.mean(np.linalg.norm(pos - pos.mean(axis=0), axis=1)))


def intra_inter(run: str, sub: str = "seed0", rnd: int = FINAL_ROUND):
    """Mean NLL on the axis a pair owns, and on the six it does not.

    Ownership is the one-to-one assignment of pairs to benchmarks that minimises
    total NLL, so the split does not assume the intended pairing held.
    """
    path = RESULTS / run / sub / "eval_test" / "eval_results.json"
    if not path.exists():
        return None, None
    rows = [r for r in json.loads(path.read_text())["results"] if r["round"] == rnd]
    if not rows:
        return None, None
    agents = sorted({r["agent"] for r in rows}, key=lambda s: int(s.split("-")[1]))
    marks = sorted({r["benchmark"] for r in rows})
    M = np.full((len(agents), len(marks)), np.nan)
    for r in rows:
        M[agents.index(r["agent"]), marks.index(r["benchmark"])] = r["mean_nll"]
    best = min(itertools.permutations(range(len(agents))),
               key=lambda p: sum(M[i, p[i]] for i in range(len(agents))))
    own = np.array([M[i, best[i]] for i in range(len(agents))])
    off = np.ones_like(M, dtype=bool)
    for i in range(len(agents)):
        off[i, best[i]] = False
    return float(own.mean()), float(M[off].mean())


def replicates() -> dict:
    """Per-split routing gains for the completed replicate data splits.

    The replicate runs live on the training host, so the extracted gains are
    checked in here rather than re-read from ``results/``.
    """
    return json.loads((DATA / "replicates.json").read_text())


def prompt_coords() -> np.ndarray:
    """Held-out prompt coordinates in the normalised trait space, shape (n, L)."""
    return np.load(DATA / "prompt_coords.npz")["coords"]


# ------------------------------------------------- seeds and derived quantities
def seeds_for(run: str) -> list[str]:
    """Scored data-split replicates of one arm, ``seed0`` first.

    Only subdirectories matching :data:`SEED_RE` that actually carry routing
    diagnostics are returned, so an in-flight replicate is skipped until it has
    been scored rather than showing up as a hole in a mean.
    """
    base = RESULTS / run
    if not base.is_dir():
        return []
    found = [
        d.name for d in base.iterdir()
        if d.is_dir() and SEED_RE.match(d.name)
        and (d / "routing_ensemble_diagnostics.json").is_file()
    ]
    return sorted(found, key=lambda s: (s != "seed0", s))


def contrast(flat: dict) -> dict:
    """Within-split contrasts from one diagnostics blob.

    Absolute NLL is not comparable across data splits -- each has its own test
    pool and its own generalist -- so every cross-split figure is built from
    these differences rather than from the raw numbers.
    """
    pooled = flat["pooled_nll"]
    learned = flat["learned_routing_nll"]
    oracle = flat["oracle_routing_nll"]
    envelope = pooled - oracle
    out = {
        "pooled": pooled, "learned": learned, "oracle": oracle,
        "gain": pooled - learned, "envelope": envelope,
        "capture": (pooled - learned) / envelope if envelope else float("nan"),
        "agreement": flat.get("routing_agreement_argmax"),
    }
    # Present only on runs scored after the ensemble metrics were added.
    for key in ("ensemble_mixture_nll", "ensemble_uniform_nll", "mean_tokens"):
        if flat.get(key) is not None:
            out[key] = flat[key]
    if "ensemble_mixture_nll" in out:
        out["gain_mixture"] = pooled - out["ensemble_mixture_nll"]
    if "ensemble_uniform_nll" in out:
        out["gain_uniform"] = pooled - out["ensemble_uniform_nll"]
    return out


def summarise(xs) -> tuple[float, float, int]:
    """Mean, sample standard deviation and count. SD is 0.0 for a single run."""
    a = np.asarray([x for x in xs if x is not None], dtype=float)
    if a.size == 0:
        return float("nan"), 0.0, 0
    return float(a.mean()), (float(a.std(ddof=1)) if a.size > 1 else 0.0), int(a.size)


def sigma_contrasts() -> dict[float, list[dict]]:
    """``{sigma_fraction: [contrast per scored split]}`` over the sweep."""
    out: dict[float, list[dict]] = {}
    for factor, run in SIGMA_ARMS:
        rows: list[dict] = []
        seen: set[str] = set()
        for candidate in SIGMA_RUN_ALIASES.get(factor, [run]):
            for sub in seeds_for(candidate):
                if sub in seen:          # one split, one row, whatever it is called
                    continue
                d = diagnostics(candidate, sub)
                if d is not None:
                    seen.add(sub)
                    rows.append(dict(contrast(d), seed=sub, run=candidate))
        if rows:
            out[factor] = sorted(rows, key=lambda r: (r["seed"] != "seed0", r["seed"]))
    return out


def roughness(ys) -> float:
    """Mean absolute second difference of a curve: how much it zigzags.

    The obvious summary of "does this sweep behave itself" is the standard
    deviation across reach, but SD answers the wrong question whenever the
    quantity has a genuine trend. The sequence-level mixture gain rises
    monotonically with reach under BOTH initialisations -- softer allocation
    mixes better even though it selects worse -- so its SD is ~0.0156 either
    way and reports no difference at all, while the two curves plainly differ.

    The second difference annihilates any straight line, so this measures
    departure from a smooth trend rather than departure from a constant, and
    separates the curves on both metrics. Points are assumed ordered by reach
    and are treated as equally spaced, which they are not (the sweep is denser
    near 0.5); that biases the statistic toward the closely spaced middle
    equally for every curve being compared, so ratios are meaningful and
    absolute values are not.
    """
    a = np.asarray([y for y in ys if y is not None], dtype=float)
    if a.size < 3:
        return float("nan")
    return float(np.abs(np.diff(a, 2)).mean())


def monotone_steps(ys) -> tuple[int, int]:
    """Rising and falling step counts of a curve, as a companion to roughness."""
    a = np.asarray([y for y in ys if y is not None], dtype=float)
    d = np.diff(a)
    return int((d > 0).sum()), int((d < 0).sum())


def theory_eq_sigma_contrasts() -> dict[str, dict[float, dict]]:
    """``{split: {sigma_fraction: contrast}}`` for the equilibrium reach sweep.

    Keyed by split first because the paired naive-vs-equilibrium comparison is
    only valid within a split, and the two splits are at different stages of
    completion.
    """
    out: dict[str, dict[float, dict]] = {}
    for factor, by_split in THEORY_EQ_SIGMA_ARMS.items():
        for split, run in by_split.items():
            d = diagnostics(run, "seed0")
            if d is not None:
                out.setdefault(split, {})[factor] = dict(
                    contrast(d), run=run, split=split)
    return out


def naive_sigma_contrasts() -> dict[str, dict[float, dict]]:
    """The naive reach sweep in the same shape, for paired differencing."""
    out: dict[str, dict[float, dict]] = {}
    for factor, rows in sigma_contrasts().items():
        for row in rows:
            out.setdefault(row["seed"], {})[factor] = row
    return out


def per_benchmark(run: str, sub: str = "seed0") -> dict[str, dict] | None:
    """Per-benchmark block of one diagnostics blob."""
    path = RESULTS / run / sub / "routing_ensemble_diagnostics.json"
    if not path.exists():
        return None
    return json.loads(path.read_text()).get("per_benchmark")


def per_benchmark_gain(run: str, sub: str = "seed0") -> dict[str, float]:
    """Routing gain per benchmark: pooled minus learned (expected)."""
    pb = per_benchmark(run, sub) or {}
    return {
        b: v["pooled_nll"] - v["learned_expected_nll"]
        for b, v in pb.items()
    }


def match_pairs(ref: np.ndarray, other: np.ndarray) -> tuple[np.ndarray, float]:
    """Match ``other``'s pairs to ``ref``'s by nearest final position.

    Pair index is an artefact of the theory solve's ordering, not an identity:
    ``pair-3`` in one run is not the same specialist as ``pair-3`` in another.
    Overlaying runs therefore requires an explicit assignment. Solved exactly by
    the Hungarian algorithm, with a brute-force fallback so the module works
    without scipy (at most 8 pairs, so 40k permutations worst case).

    :returns: ``(perm, cost)`` where ``other[perm[i]]`` matches ``ref[i]``.
    """
    cost = np.linalg.norm(ref[:, None, :] - other[None, :, :], axis=2)
    try:
        from scipy.optimize import linear_sum_assignment
        _, perm = linear_sum_assignment(cost)
    except ImportError:  # pragma: no cover - exercised only without scipy
        n = cost.shape[0]
        perm = min(itertools.permutations(range(n)),
                   key=lambda p: sum(cost[i, p[i]] for i in range(n)))
        perm = np.asarray(perm)
    perm = np.asarray(perm)
    return perm, float(sum(cost[i, perm[i]] for i in range(len(perm))))


def history_slim(run: str, sub: str = "seed0") -> dict | None:
    """Positions and per-round diagnostics from one run, without the prompts.

    ``history.json`` is ~66 MB, almost all of it logged prompts and responses.
    This keeps only what the figures plot and drops the rest immediately.
    """
    path = RESULTS / run / sub / "history.json"
    if not path.exists():
        return None
    records = json.loads(path.read_text())
    first, last = records[0], records[-1]
    theory = first.get("theory_init", {}) or {}

    names = sorted(last.get("pair_positions", {}),
                   key=lambda s: int(s.split("-")[1]))
    if not names:            # hard-routing arms log no pair_positions
        groups = theory.get("sft_merge_groups_resolved") or []
        names = [g["train_as"] for g in groups]
        members = {g["train_as"]: g["names"] for g in groups}
        traj = np.array([
            [rec["positions"][members[n][0]] for n in names] for rec in records
        ])
    else:
        traj = np.array([
            [rec["pair_positions"][n] for n in names] for rec in records
        ])

    # theory_init keys pairs as "pair_<memberA>_<memberB>"; bridge to "pair-N".
    bridge = {
        g["train_as"]: "pair_" + "_".join(g["names"])
        for g in (theory.get("sft_merge_groups_resolved") or [])
    }
    tpos = theory.get("pair_positions") or {}
    dom = theory.get("pair_dominant_axis") or {}
    theory_pos = np.array([tpos[bridge[n]] for n in names]) if bridge and tpos else None
    dominant = [int(dom.get(bridge.get(n, ""), -1)) for n in names]

    def _stack(key):
        if key not in last:
            return None
        return np.array([[rec[key][n] for n in names] for rec in records])

    return {
        "run": run, "seed": sub, "pair_names": names, "n_rounds": len(records),
        "positions": traj,                       # (T, P, L)
        "theory_positions": theory_pos,          # (P, L) or None
        "dominant_axis": dominant,               # (P,)
        "within_pair_l2": [
            rec.get("agent_geometry", {}).get("within_merge_l2") for rec in records
        ],
        "pair_u_pool": _stack("pair_u_pool"),
        "pair_share_batch": _stack("pair_share_batch"),
    }
